---
title: "p8105_hw5_fw2334"
author: "Frances Williams"
date: "11/6/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Problem 1

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

iris_num_vec = function(x) {
  if (is.numeric(x)) {
    replace_na(x, mean(x, na.rm = TRUE))
  }
  else if (is.character(x)) {
    replace_na(x, "virginica")
  }
}


df = map_df(iris_with_missing, iris_num_vec)

```


# Problem 2

```{r}
patient_files = list.files(path = "./files", full.names = TRUE)

experiment_df = patient_files %>% 
  map_df(read.csv) %>% 
  mutate(patient_id = tools::file_path_sans_ext(basename(patient_files))) %>% 
  separate(patient_id, into = c("arm", "id"), sep = "_") %>%
  mutate(subject = as.factor(id)) %>% 
  pivot_longer(week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "value")

exp_plot = experiment_df %>% 
  ggplot(aes(x = week, y = value, color = subject, group = subject)) +
  geom_line() + 
  geom_point() +
  facet_wrap(~arm)

exp_plot


```


# Problem 3

setting beta1 = 0
```{r}
set.seed(10)

sim_regression = function(n = 30, beta0 = 2, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, mean = 0, sd = sqrt(50))
  )
  
  ls_fit = lm(y ~ x, data = sim_data) %>% broom::tidy()
  
  tibble(
    beta1_hat = ls_fit[[2,2]],
    p_value = ls_fit[[2,5]]
  )
}


output = vector("list", 10000)

for (i in 1:10000) {
  output[[i]] = sim_regression(beta1 = 0)
}

sim_results = bind_rows(output)

```

Creating list for beta1 ranging from 0 to 6
```{r}

n_list = list("b1_0" = 0, 
              "b1_1" = 1, 
              "b1_2" = 2, 
              "b1_3" = 3,
              "b1_4" = 4,
              "b1_5" = 5,
              "b1_6" = 6)
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(100, sim_regression(n_list[[i]])) %>% 
    bind_rows
}

```

